version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./videos:/app/videos
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://admin_user:Gbc}W<iN*+L&%j6M@db:5432/mydatabase # DB connection string

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: Gbc}W<iN*+L&%j6M
    ports:
      - "5432:5432" # Exposing PostgreSQL's default port
